alt_article_APP/urls.py
from django.urls import path
from . import views

app_name = 'alt_article_APP'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

alt_article_WWW/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('alt_article/', include('alt_article_APP.urls')),
]

alt_article_APP/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Tag(models.Model):
    name = models.CharField(max_length=30)

class Domena_WWW(models.Model):
    URL = models.URLField()
    rating = models.IntegerField(default=0)
    catergory = models.CharField(max_length=100)    # strony polityczne: lewa, prawa, centro, tech, culture, plotki, news, finanse, itd, podobnie jak w newsvoice
    summary = models.TextField()

class Alt_url_link(models.Model):
    URL = models.URLField()
    rating = models.IntegerField(default=0)
    domena_WWW = models.ForeignKey(Domena_WWW, on_delete=models.SET_NULL, null=True)   # każda domena serwis WWW powienien też być klasą  (A nie tylko models.URLField()), bo powienien miec swoja ocenę, link, atrybuty(jaki serwis), komentarze itd
    
class Alt_article(models.Model):
    title = models.CharField(max_length=200)
    alt_url_link = models.ForeignKey(Alt_url_link, on_delete=models.SET_NULL, null=True)     # alt_url_link - tez powienine byc klasa (A nie tylko models.URLField()), bo powienien miec swoja ocenę, link, zrodlo, atrybuty(jaki serwis/domena), komentarze itd, ocena domeny też ma wpływ na ocenę alt_link
    summary = models.TextField()
    pub_date = models.DateTimeField('date published')
    tag = models.ManyToManyField(Tag)

alt_article_APP/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.db.models import F

from .models import Choice, Question

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'alt_article_APP/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'alt_article_APP/results.html'

class DetailView(generic.DetailView):
    model = Question
    template_name = 'alt_article_APP/detail.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.filter(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, "alt_article_APP/detail.html", {
            'question': question,
            'errorMessage': "Nie wybrales żadnej odpowiedzi.",
        })
    else:
        # update() with F() is doing work that blocks occuring hazard (race condition)
        selected_choice.update( votes = F('votes')+1 )
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('alt_article_APP:results', args=(question.id,)))

alt_article_APP/templates/alt_article_APP/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Detail view</title>
</head>
<body>
    <h1>{{question.question_text}}</h1>
    {% if errorMessage %}
        <p><strong>{{ errorMessage }}</strong></p>
    {% endif %}

    <form action="{% url 'alt_article_APP:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
                <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
        {% endfor %}
        <input type="submit" value="Vote">
    </form>
</body>
</html>

alt_article_APP/templates/alt_article_APP/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home Page</title>
</head>
<body>
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
            <li><a href=" {% url 'alt_article_APP:detail' question.id %}">{{question.question_text}}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p> No article is avaiable</p>
    {% endif %}
</body>
</html>

alt_article_APP/templates/alt_article_APP/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Result Page</title>
</head>
<body>
    <h1>{{question.question_text}}</h1>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} ma głosów {{choice.votes}} vote{{choice.votes|pluralize}}</li>
    {% endfor %}

    <a href="{% url 'alt_article_APP:detail' question.id %}">Chcesz zagłosować jeszcze raz?</a>
</body>
</html>